### ISSUE TITLE
Inquiry About Block and Apology

### ISSUE THREAD

**Issue by Monishnyr** [casdoor/casdoor-java-sdk#103]
@hsluoyz 
I recently submitted PR [#102](https://github.com/casdoor/casdoor-java-sdk/pull/102) for the setPassword API implementation in the Casdoor Java SDK. However, I noticed that my PR was closed, and I am currently unable to raise any issues or communicate directly through the repository.

I would like to understand the reason for this and apologize if I have done anything wrong or if my actions were against the project's guidelines. My intention was solely to contribute to the project and help improve the SDK.

Could you please provide me with some feedback or guidance on how I can rectify any issues? I am eager to learn and make any necessary adjustments to align with the project's standards.

Additionally, I kindly request to be unblocked. I assure you that I will adhere to all guidelines and avoid any mistakes in the future.

**Comment by hsluoyz** [comment]
@Monishnyr you have created several low-quality PRs, wasting the PR numbers and pages. The existing PRs are hard to improve. Maybe letting a new person create a PR should be faster and more efficient. This is not a project for beginner learning. If you work for a company, let a more senior developer in your company take this work.

This issue will be deleted shortly too. Don't use issues for this kind of things.
