### ISSUE TITLE
Add methods such as getSigninUrl(), getSignupUrl() etc.

### ISSUE THREAD

**Issue by seriouszyx** [casdoor/casdoor-java-sdk#14]
Currently, developers using Casdoor must import [casdoor-js-sdk](https://github.com/casdoor/casdoor-js-sdk/blob/master/src/sdk.ts) on the front-end while importing [casdoor-java-sdk](https://github.com/casdoor/casdoor-java-sdk) on the back-end. If not, they must construct URLs for the signin and signup pages by themselves.

I‘m considering providing constructed URLs from the SDK so that developers can redirect pages on the back-end.

**Comment by hsluoyz** [comment]
@seriouszyx good idea. Please port these APIs to Java: https://github.com/casdoor/casdoor-go-sdk/commit/984a325cb96d129c07d82b8d395caf580c4d4821

Tip: Java can use default function args to make the API look better.

**Comment by seriouszyx** [comment]
done
