### ISSUE TITLE
please support get role info API in Java SDK

### ISSUE THREAD

**Issue by mingxinkejian** [casdoor/casdoor-java-sdk#28]
hi，developer!
user login by oauth2.0，but can't get role info。
please support the sdk to method of get role info！

**Comment by hsluoyz** [comment]
@Resulte plz add this PR: https://github.com/casdoor/casdoor/pull/929 also to this java-sdk

**Comment by hsluoyz** [comment]
@mingxinkejian can you make a PR?

**Comment by Resulte** [comment]
Casdoor is already support get role info by get user API. So you can just use java-sdk's GetUser() to get role info. @mingxinkejian
