### ISSUE TITLE
feat: Enhance and improve basic features to support casdoor-springboot-starter development

### ISSUE THREAD

**Issue by tangyang9464** [casdoor/casdoor-java-sdk#3]
ref: [casdoor-spring-boot-starter](https://github.com/casdoor/casdoor-spring-boot-starter/issues/1) [README](https://github.com/casdoor/casdoor-spring-boot-starter/pull/4)

casdoor-springboot-starter depends on this sdk, so it must wait for the completion of this sdk

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by hsluoyz** [comment]
@tangyang9464 I think @Kininaru maybe doesn't have time for this moment. Can you do it instead?
