### ISSUE TITLE
getUserProfileUrl format is wrong

### ISSUE THREAD

**Issue by dfang** [casdoor/casdoor-java-sdk#40]
https://github.com/casdoor/casdoor-java-sdk/blob/master/src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java#L151

https://github.com/casdoor/casdoor-go-sdk/blob/v0.20.1/casdoorsdk/url.go#L46

`/users/<org>/<username>`

**Comment by hsluoyz** [comment]
@dfang hi, can you make a PR to fix it?
