### ISSUE TITLE
Access token not found in JWT payload

### ISSUE THREAD

**Issue by zeekrs** [casdoor/casdoor-java-sdk#55]
<img width="1353" alt="CleanShot 2023-08-08 at 22 36 54@2x" src="https://github.com/casdoor/casdoor-java-sdk/assets/87763555/c0512bab-1dd4-4dba-80e2-0ead5e809e3f">
Is there any issue with my jwttoken ?
i'm upgrade the  spring-starter version to 1.9.0 and the sdk version is 1.16.1

parse the jwttoken it has 60 size claims 
but haven't  access_token 
#54 #53 #

**Comment by hsluoyz** [comment]
@zeekrs use latest Casdoor version

**Comment by hsluoyz** [comment]
@zeekrs I mean latest "Casdoor" version, latest is v1.383.0: https://github.com/casdoor/casdoor/releases/tag/v1.383.0

Not this Java SDK

**Comment by zeekrs** [comment]
thx

**Comment by zeekrs** [comment]
sorry , i'm upgrade the casdoor version to , The problem still exists. 
i view the casdoor  code on master  branch.  token_jwt.go line 226 function generateJwtToken
i think it never put a key of access_token in the claims   (i'm not a gopher) 
why the java-sdk will get a access_token in claims ? 
dos this a bug  or some wrong with myself , I have no idea

**Comment by zhengwangwang** [comment]
I encountered the same problem. This variable claimsSet in parseJwtToken(String token) method is parsed userjson，but not the accessToken.
in v1.15.0 readValue from payloadJson.toString()
