### ISSUE TITLE
The interface update frequency of sdk cannot keep up with the main branch of casdoor. 

### ISSUE THREAD

**Issue by CharsonYang** [casdoor/casdoor-java-sdk#65]
The API interface in the latest version of casdoor-java-sdk does not match the casdoor interface. For example: the attributes of the object "CasdoorResponse" returned by the api interface in sdk is inconsistent with the "Response" attributes of casdoor.

**Comment by hsluoyz** [comment]
@CharsonYang I think they are the same. Why do you say different? Can you provide more details?

**Comment by hsluoyz** [comment]
Closed as stale
