### ISSUE TITLE
Buy Product API using Java

### ISSUE THREAD

**Issue by MonishK2002** [casdoor/casdoor-java-sdk#90]
Hi team,
We are integrating our application to casdoor/casbin for authentication, authorization, and subscription management. Just so, you know – authentication and authorization were completed successfully. But, while doing for subscription, we faced an issue integrating Buy-Product API in casdoor java SDK. We found that API is available only in GO language not for JAVA langauge. So, can you please guide us/provide some way to integrate that buy-product API into our Java application? 

https://github.com/search?q=repo%3Acasdoor%2Fcasdoor-go-sdk%20buyproduct&type=code

**Comment by MonishK2002** [comment]
Hi team,
Thank you for getting back to me about the enhancement. The Buy-Product API is currently unsupported in the Casdoor Java SDK. To integrate this functionality into our application, we would appreciate any guidance or solutions on how to do this.

**Comment by MonishK2002** [comment]
Hi Casdoor Team,

I hope this message finds you well.

I have raised an issue with the Casdoor Java SDK version 1.22.1. I noticed that it has been fixed and the new version 1.32.0 was released on October 10th. However, in my Spring Boot application, the pom.xml file is still pointing to the old version (1.22.1).

Please guide how to update the pom.xml file to reflect the latest version (1.32.0) of the Casdoor SDK.

Thank you for taking the time to look into this matter.

**Comment by hsluoyz** [comment]
@MonishK2002 can you make a PR to: https://github.com/casdoor/casdoor-spring-boot-starter to update the casdoor-java-sdk version?

**Comment by MonishK2002** [comment]
I have created a PR to update the casdoor-java-sdk version in the casdoor-spring-boot-starter project You can review it at your convenience:

PR Link: 
           https://github.com/casdoor/casdoor-spring-boot-starter/pull/44

Thank you for your prompt assistance and support

**Comment by MonishK2002** [comment]
@hsluoyz 
           I noticed that my recent PR to update the casdoor-java-sdk version in the casdoor-spring-boot-starter project was closed, with the following checks:

1 successful
1 failing
1 pending
Could you please provide more details or feedback on the failing and pending checks? I want to ensure that any necessary adjustments are made and that the update can be successfully integrated.

Thank you for your assistance and guidance.

**Comment by hsluoyz** [comment]
@MonishK2002 don't comment on this issue again. It's over. Move on to next issue/PR
