### ISSUE TITLE
[feature] some User fields are missing

### ISSUE THREAD

**Issue by tysunrain** [casdoor/casdoor-java-sdk#96]
- I can't get field ‘groups’  by using casdoor-java-sdk  ,but the field appears in casdoor-go-sdk/casdoorsdk/user.go  
- There are some differences in user entity between go-sdk and java-sdk

![image](https://github.com/user-attachments/assets/95c4dabe-d6db-44b0-b3d8-fbcfb3dcafc5)
---------------------------------------------------------------------------------------------------------------
![image](https://github.com/user-attachments/assets/a06bb641-8d36-48b0-9db9-306061a035c9)

**Comment by hsluoyz** [comment]
@tysunrain can you make a PR to fix it?
